# Generated by Django 5.1.4 on 2026-05-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodingChallenge',
        ),
    ]
